name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
      presentation:
        - bioinfo_ws
        - develop_and_collab
    permissions:
      contents: write
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Ensure build dir exists
        run: mkdir -p build
      -
        name: Copy images directory (if exists)
        run: if [[ -d img ]]; then cp -R img build/img; fi
      -
        name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: ${{ matrix.presentation }}/README.md -o build/${{ matrix.presentation }}/index.html
        env:
          MARP_USER: root:root
      - 
        name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: ${{ matrix.presentation }}/README.md --allow-local-files -o build/${{ matrix.presentation }}/README.pdf
        env:
          MARP_USER: root:root
      -
        name: Marp Build (README.pptx)
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: ${{ matrix.presentation }}/README.md --allow-local-files -o build/${{ matrix.presentation }}/README.pptx
        env:
          MARP_USER: root:root
      - 
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/